var sub='one two three four five six seven eight nine ten'.split(' ');function validate_target_amnt(){0>=document.getElementById('capital').value?(document.getElementById('error').innerHTML=' Please enter valid target amount',document.getElementById('capital').value='',c(),document.getElementById('myform').reset(),document.getElementById('capital').focus()):document.getElementById('error').innerHTML=''}
function c(){for(var a=0;a<sub.length;a++)document.getElementById('amnt_'+sub[a]).defaultValue='',document.getElementById('amnt_'+sub[a]).value='',rv('amnt_'+sub[a]),document.getElementById('gift_'+sub[a]).defaultValue='',document.getElementById('gift_'+sub[a]).value='',rv('gift_'+sub[a])}function ca(){c(),document.getElementById('myform').reset(),document.getElementById('capital').focus()}function rv(a){document.getElementById(a).style.borderColor='#47bbff';document.getElementById(a).style.borderWidth='1px'}function rm(a){document.getElementById(a).style.borderColor='';document.getElementById(a).style.borderWidth=''}
function restore(){document.getElementById('error').innerHTML='';var a=Number(document.getElementById('capital').value);c();document.getElementById('myform').reset();document.getElementById('capital').value=a;updateTotal()}function validate(a,e){a--;e='undefined'!==typeof e?e:'amnt_';0>document.getElementById(e+sub[a]).value?(document.getElementById(e+sub[a]).style.borderColor='red',document.getElementById(e+sub[a]).style.borderWidth='3px'):rm(e+sub[a])}
function updateTotal(){var a=[1,1,2,2,3,4,4,5,5,10],e=0,b=0,l=b=0,k=0,d=Number(document.getElementById('capital').value);found=!1;var b=co(d,[25,12,10,6,4,2,1,.8,.4,.1],a),h=b.gifts;b.flag&&(h=ac(h,a,b.goal));for(a=0;a<sub.length&&0<d;a++){b=0<=h[0][a]?h[0][a]:Number(document.getElementById('amnt_'+sub[a]).value);document.getElementById('amnt_'+sub[a]).defaultValue=b;var g=0<=h[1][a]?h[1][a]:Number(document.getElementById('gift_'+sub[a]).value);document.getElementById('gift_'+sub[a]).defaultValue=
g;l+=0<g?g:0;b=0<g&&0<b?f(b*g):0;document.getElementById('sub_'+sub[a]).value=b;e=f(e+b);document.getElementById('cu_'+sub[a]).value=e;b=0<g?5*g:0;document.getElementById('pros_'+sub[a]).value=b;k+=b;b=f(100*e/d);document.getElementById('cumu_'+sub[a]).value=b}document.getElementById('gift_total').value=l;document.getElementById('pros_total').value=k;document.getElementById('cu_total').value=f(e);e>d?(document.getElementById('amount_reach').innerHTML='Total can\'t exceed target amount',document.getElementById('cu_total').style.borderColor=
'black',document.getElementById('cu_total').style.background='red',document.getElementById('cu_total').style.color='white',document.getElementById('capital').style.borderColor='black',document.getElementById('capital').style.background='red'):(document.getElementById('amount_reach').innerHTML='',document.getElementById('cu_total').style.borderColor='none',document.getElementById('cu_total').style.background='#47bbff',document.getElementById('cu_total').style.color='white',document.getElementById('capital').style.borderColor=
'none',document.getElementById('capital').style.background='#47bbff');document.getElementById('capital').style.color='white'}
function co(a,e,b){for(var l=[[],[]],k=0,d=a,h=!1,g=0;g<sub.length&&0<a;g++){var n=f(Number(a)*e[g]/100);l[0].push(n);var p=Number(document.getElementById('amnt_'+sub[g]).value);0<=p&&''!=document.getElementById('amnt_'+sub[g]).style.border&&'solid'!=document.getElementById('amnt_'+sub[g]).style.border?document.getElementById('amnt_'+sub[g]).defaultValue=n:(n=p,l[0][g]=-1,h=!0);for(var m=0;0<n&&m+1<=b[g]&&f(n*(m+1))<=a&&(f(n*(m+1)+k)<=a||0==k);)m++;l[1].push(m);p=Number(document.getElementById('gift_'+
sub[g]).value);0<=p&&''!=document.getElementById('gift_'+sub[g]).style.border&&'solid'!=document.getElementById('gift_'+sub[g]).style.border?document.getElementById('gift_'+sub[g]).defaultValue=m:(m=p,l[1][g]=-1,h=!0);0<n&&0<m&&(k=f(k+n*m));(-1==l[0][g]||-1==l[1][g])&&0<n&&0<m&&(d=f(d-n*m))}!h&&k<a&&(l=aw(l,a-k));return{gifts:l,goal:0<d?d:0,flag:h}}
function ac(a,e,b){var n=a[0][0];for(var m=!1,l=!1,d=0;d<sub.length;d++){0<a[0][d]?(m=!0,(-1==n||n>a[0][d]&&a[0][d]>0)&&(n=a[0][d])):(-1==n||n>Number(document.getElementById("amnt_"+sub[d]).value)&&Number(document.getElementById("amnt_"+sub[d]).value)>0)&&(n=Number(document.getElementById("amnt_"+sub[d]).value));l=0<a[1][d]||l;if(0<a[0][d]&&0<a[1][d]){for(var h=0;f((h+1)*a[0][d])<=b&&h+1<=e[d];)h++;b=f(b-h*a[0][d]);a[1][d]=h}}for(;l&&0<b&&b>=n;)for(d=0;d<sub.length;d++)h=a[1][d],i=0<a[0][d]?a[0][d]:Number(document.getElementById('amnt_'+sub[d]).value),0<=a[1][d]&&0<i&&i<=b&&(b=f(b-i),a[1][d]=h+1);0!=b&&m&&(a=aw(a,b));return a}
function aw(a,e){var b=gd(a);a[1][b]=0==a[1][b]&&-1!=a[0][b]?1:a[1][b];a[0][b]=f(a[0][b]+e/a[1][b]);return a}function gd(a){for(var e=0,b=0;b<sub.length;b++)(-1==a[0][e]||-1==a[1][e])&&-1<a[0][b]&&-1<a[1][b]&&(e=b),0<a[1][b]&&-1<a[0][b]&&a[1][e]!=a[1][b]&&(1==a[1][b]||a[1][b]<a[1][e]&&(0==a[1][b]%2||1==a[1][b]%2&&1==a[1][e]%2)||1!=a[1][e]&&1==a[1][e]%2&&0==a[1][b]%2)&&(e=b);return e}function f(a){return Number(Number(a).toFixed(0))||0};