# Generated by Django 3.1.2 on 2020-10-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points_worth',
            field=models.IntegerField(default=10),
        ),
    ]
